// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: log.proto

package protogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BuildDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeVersion   string                 `protobuf:"bytes,1,opt,name=nodeVersion,proto3" json:"nodeVersion,omitempty"`
	AppVersion    string                 `protobuf:"bytes,2,opt,name=appVersion,proto3" json:"appVersion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildDetails) Reset() {
	*x = BuildDetails{}
	mi := &file_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildDetails) ProtoMessage() {}

func (x *BuildDetails) ProtoReflect() protoreflect.Message {
	mi := &file_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildDetails.ProtoReflect.Descriptor instead.
func (*BuildDetails) Descriptor() ([]byte, []int) {
	return file_log_proto_rawDescGZIP(), []int{0}
}

func (x *BuildDetails) GetNodeVersion() string {
	if x != nil {
		return x.NodeVersion
	}
	return ""
}

func (x *BuildDetails) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

type Log struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServiceName    string                 `protobuf:"bytes,1,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	BuildDetails   *BuildDetails          `protobuf:"bytes,2,opt,name=buildDetails,proto3" json:"buildDetails,omitempty"`
	Level          string                 `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`
	Message        string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Stack          string                 `protobuf:"bytes,5,opt,name=stack,proto3" json:"stack,omitempty"`
	RequestId      string                 `protobuf:"bytes,6,opt,name=requestId,proto3" json:"requestId,omitempty"`
	RequestUrl     string                 `protobuf:"bytes,7,opt,name=requestUrl,proto3" json:"requestUrl,omitempty"`
	RequestMethod  string                 `protobuf:"bytes,8,opt,name=requestMethod,proto3" json:"requestMethod,omitempty"`
	UserAgent      string                 `protobuf:"bytes,9,opt,name=userAgent,proto3" json:"userAgent,omitempty"`
	RemoteIp       string                 `protobuf:"bytes,10,opt,name=remoteIp,proto3" json:"remoteIp,omitempty"`
	ResponseStatus string                 `protobuf:"bytes,11,opt,name=responseStatus,proto3" json:"responseStatus,omitempty"`
	ResponseTime   string                 `protobuf:"bytes,12,opt,name=responseTime,proto3" json:"responseTime,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_log_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_log_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_log_proto_rawDescGZIP(), []int{1}
}

func (x *Log) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Log) GetBuildDetails() *BuildDetails {
	if x != nil {
		return x.BuildDetails
	}
	return nil
}

func (x *Log) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Log) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Log) GetStack() string {
	if x != nil {
		return x.Stack
	}
	return ""
}

func (x *Log) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Log) GetRequestUrl() string {
	if x != nil {
		return x.RequestUrl
	}
	return ""
}

func (x *Log) GetRequestMethod() string {
	if x != nil {
		return x.RequestMethod
	}
	return ""
}

func (x *Log) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *Log) GetRemoteIp() string {
	if x != nil {
		return x.RemoteIp
	}
	return ""
}

func (x *Log) GetResponseStatus() string {
	if x != nil {
		return x.ResponseStatus
	}
	return ""
}

func (x *Log) GetResponseTime() string {
	if x != nil {
		return x.ResponseTime
	}
	return ""
}

func (x *Log) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           bool                   `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_log_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_log_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_log_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

var File_log_proto protoreflect.FileDescriptor

const file_log_proto_rawDesc = "" +
	"\n" +
	"\tlog.proto\x12\x06logboy\x1a\x1fgoogle/protobuf/timestamp.proto\"P\n" +
	"\fBuildDetails\x12 \n" +
	"\vnodeVersion\x18\x01 \x01(\tR\vnodeVersion\x12\x1e\n" +
	"\n" +
	"appVersion\x18\x02 \x01(\tR\n" +
	"appVersion\"\xcb\x03\n" +
	"\x03Log\x12 \n" +
	"\vserviceName\x18\x01 \x01(\tR\vserviceName\x128\n" +
	"\fbuildDetails\x18\x02 \x01(\v2\x14.logboy.BuildDetailsR\fbuildDetails\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x14\n" +
	"\x05stack\x18\x05 \x01(\tR\x05stack\x12\x1c\n" +
	"\trequestId\x18\x06 \x01(\tR\trequestId\x12\x1e\n" +
	"\n" +
	"requestUrl\x18\a \x01(\tR\n" +
	"requestUrl\x12$\n" +
	"\rrequestMethod\x18\b \x01(\tR\rrequestMethod\x12\x1c\n" +
	"\tuserAgent\x18\t \x01(\tR\tuserAgent\x12\x1a\n" +
	"\bremoteIp\x18\n" +
	" \x01(\tR\bremoteIp\x12&\n" +
	"\x0eresponseStatus\x18\v \x01(\tR\x0eresponseStatus\x12\"\n" +
	"\fresponseTime\x18\f \x01(\tR\fresponseTime\x128\n" +
	"\ttimestamp\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x1c\n" +
	"\bResponse\x12\x10\n" +
	"\x03ack\x18\x01 \x01(\bR\x03ack2B\n" +
	"\n" +
	"LogService\x124\n" +
	"\x11ReceiveLogsStream\x12\v.logboy.Log\x1a\x10.logboy.Response(\x01B\x17Z\x15gRPC-gateway/protogenb\x06proto3"

var (
	file_log_proto_rawDescOnce sync.Once
	file_log_proto_rawDescData []byte
)

func file_log_proto_rawDescGZIP() []byte {
	file_log_proto_rawDescOnce.Do(func() {
		file_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_log_proto_rawDesc), len(file_log_proto_rawDesc)))
	})
	return file_log_proto_rawDescData
}

var file_log_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_log_proto_goTypes = []any{
	(*BuildDetails)(nil),          // 0: logboy.BuildDetails
	(*Log)(nil),                   // 1: logboy.Log
	(*Response)(nil),              // 2: logboy.Response
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_log_proto_depIdxs = []int32{
	0, // 0: logboy.Log.buildDetails:type_name -> logboy.BuildDetails
	3, // 1: logboy.Log.timestamp:type_name -> google.protobuf.Timestamp
	1, // 2: logboy.LogService.ReceiveLogsStream:input_type -> logboy.Log
	2, // 3: logboy.LogService.ReceiveLogsStream:output_type -> logboy.Response
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_log_proto_init() }
func file_log_proto_init() {
	if File_log_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_log_proto_rawDesc), len(file_log_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_log_proto_goTypes,
		DependencyIndexes: file_log_proto_depIdxs,
		MessageInfos:      file_log_proto_msgTypes,
	}.Build()
	File_log_proto = out.File
	file_log_proto_goTypes = nil
	file_log_proto_depIdxs = nil
}
